name: Compile data

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH debug
        if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Compile data
        run: bun run compile

      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update compiled data"

  deploy:
    needs: compile
    uses: ./.github/workflows/deploy.yaml
