name: Deploy web app

on:
  push:
    branches:
      - main

  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      
      - name: Summary info
        run: echo Commit && git rev-parse HEAD && cat ./public/metadata.json

      - if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Install packages
        run: yarn install

      - name: Build app
        run: yarn build

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: true
          folder: dist
