name: Deploy web app

on:
  push:
    branches:
      - main

  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Summary info
        run: echo Commit && git rev-parse HEAD && cat ./public/metadata.json

      - name: SSH debug
        if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install packages
        run: bun install

      - name: Build app
        run: bun run build

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: true
          folder: dist
