name: Compile data and deploy web app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-web-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install packages
        run: yarn install

      - name: Compile data
        run: yarn compile

      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update compiled data"

      - name: Build app
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          keep_files: false
          publish_branch: gh-pages
          publish_dir: dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
