name: Test web app and scripts

on:
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install packages
        run: bun install

      - if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Run test
        run: bun run build

  test-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install packages
        run: bun install

      - if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Run test
        run: bun run test:types

  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install packages
        run: bun install

      - if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Run test
        run: bun run test:lint
